/* Copyright (c) 2009, Real-Time Innovations, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * - Redistributions of source code must retain the above copyright notice,
 *   this list of conditions and the following disclaimer.
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in the
 *   documentation and/or other materials provided with the distribution.
 * - Neither the name of Real-Time Innovations, Inc. nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

package org.omg.dds.domain.discovery;

import org.omg.dds.core.ValueType;
import org.omg.dds.core.policy.DeadlineQosPolicy;
import org.omg.dds.core.policy.DestinationOrderQosPolicy;
import org.omg.dds.core.policy.DurabilityQosPolicy;
import org.omg.dds.core.policy.DurabilityServiceQosPolicy;
import org.omg.dds.core.policy.GroupDataQosPolicy;
import org.omg.dds.core.policy.LatencyBudgetQosPolicy;
import org.omg.dds.core.policy.LifespanQosPolicy;
import org.omg.dds.core.policy.LivelinessQosPolicy;
import org.omg.dds.core.policy.OwnershipQosPolicy;
import org.omg.dds.core.policy.OwnershipStrengthQosPolicy;
import org.omg.dds.core.policy.PartitionQosPolicy;
import org.omg.dds.core.policy.PresentationQosPolicy;
import org.omg.dds.core.policy.ReliabilityQosPolicy;
import org.omg.dds.core.policy.TopicDataQosPolicy;
import org.omg.dds.core.policy.UserDataQosPolicy;


/**
 * DDS/PublicationBuiltinTopicData.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from dds_rtf2_dcps.idl
 * Wednesday, September 16, 2009 9:06:02 AM CDT
 */
public interface PublicationBuiltinTopicData
extends ValueType<PublicationBuiltinTopicData> {
    /**
     * @param key the key to set
     */
    public void setKey(BuiltinTopicKey key);

    /**
     * @return the key
     */
    public BuiltinTopicKey getKey();

    /**
     * @param participantKey the participantKey to set
     */
    public void setParticipantKey(BuiltinTopicKey participantKey);

    /**
     * @return the participantKey
     */
    public BuiltinTopicKey getParticipantKey();

    /**
     * @param topicName the topicName to set
     */
    public void setTopicName(String topicName);

    /**
     * @return the topicName
     */
    public String getTopicName();

    /**
     * @param typeName the typeName to set
     */
    public void setTypeName(String typeName);

    /**
     * @return the typeName
     */
    public String getTypeName();

    /**
     * @param durability the durability to set
     */
    public void setDurability(DurabilityQosPolicy durability);

    /**
     * @return the durability
     */
    public DurabilityQosPolicy getDurability();

    /**
     * @param durabilityService the durabilityService to set
     */
    public void setDurabilityService(
            DurabilityServiceQosPolicy durabilityService);

    /**
     * @return the durabilityService
     */
    public DurabilityServiceQosPolicy getDurabilityService();

    /**
     * @param latencyBudget the latencyBudget to set
     */
    public void setLatencyBudget(
            LatencyBudgetQosPolicy latencyBudget);

    /**
     * @return the latencyBudget
     */
    public LatencyBudgetQosPolicy getLatencyBudget();

    /**
     * @param userData the userData to set
     */
    public void setUserData(UserDataQosPolicy userData);

    /**
     * @return the userData
     */
    public UserDataQosPolicy getUserData();

    /**
     * @param ownershipStrength the ownershipStrength to set
     */
    public void setOwnershipStrength(
            OwnershipStrengthQosPolicy ownershipStrength);

    /**
     * @return the ownershipStrength
     */
    public OwnershipStrengthQosPolicy getOwnershipStrength();

    /**
     * @param destinationOrder the destinationOrder to set
     */
    public void setDestinationOrder(
            DestinationOrderQosPolicy destinationOrder);

    /**
     * @return the destinationOrder
     */
    public DestinationOrderQosPolicy getDestinationOrder();

    /**
     * @param topicData the topicData to set
     */
    public void setTopicData(TopicDataQosPolicy topicData);

    /**
     * @return the topicData
     */
    public TopicDataQosPolicy getTopicData();

    /**
     * @param groupData the groupData to set
     */
    public void setGroupData(GroupDataQosPolicy groupData);

    /**
     * @return the groupData
     */
    public GroupDataQosPolicy getGroupData();

    /**
     * @param deadline the deadline to set
     */
    public void setDeadline(DeadlineQosPolicy deadline);

    /**
     * @return the deadline
     */
    public DeadlineQosPolicy getDeadline();

    /**
     * @param liveliness the liveliness to set
     */
    public void setLiveliness(LivelinessQosPolicy liveliness);

    /**
     * @return the liveliness
     */
    public LivelinessQosPolicy getLiveliness();

    /**
     * @param reliability the reliability to set
     */
    public void setReliability(ReliabilityQosPolicy reliability);

    /**
     * @return the reliability
     */
    public ReliabilityQosPolicy getReliability();

    /**
     * @param lifespan the lifespan to set
     */
    public void setLifespan(LifespanQosPolicy lifespan);

    /**
     * @return the lifespan
     */
    public LifespanQosPolicy getLifespan();

    /**
     * @param ownership the ownership to set
     */
    public void setOwnership(OwnershipQosPolicy ownership);

    /**
     * @return the ownership
     */
    public OwnershipQosPolicy getOwnership();

    /**
     * @param presentation the presentation to set
     */
    public void setPresentation(PresentationQosPolicy presentation);

    /**
     * @return the presentation
     */
    public PresentationQosPolicy getPresentation();

    /**
     * @param partition the partition to set
     */
    public void setPartition(PartitionQosPolicy partition);

    /**
     * @return the partition
     */
    public PartitionQosPolicy getPartition();

}
