/* Copyright (c) 2009, Real-Time Innovations, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * - Redistributions of source code must retain the above copyright notice,
 *   this list of conditions and the following disclaimer.
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in the
 *   documentation and/or other materials provided with the distribution.
 * - Neither the name of Real-Time Innovations, Inc. nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

package org.omg.dds.subscription;

import org.omg.dds.infrastructure.InstanceHandle;
import org.omg.dds.infrastructure.Status;
import org.omg.dds.spi.ServiceImpl;
import org.omg.dds.spi.StatusFactory;


/**
 * DDS/LivelinessChangedStatus.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from dds_rtf2_dcps.idl
 * Wednesday, September 16, 2009 9:06:02 AM CDT
 */
public abstract class LivelinessChangedStatus
extends Status<LivelinessChangedStatus, DataReader<?>> {
    // -----------------------------------------------------------------------
    // Constants
    // -----------------------------------------------------------------------

    private static final long serialVersionUID = -2646782323276659024L;



    // -----------------------------------------------------------------------
    // Object Lifecycle
    // -----------------------------------------------------------------------

    public static LivelinessChangedStatus create() {
        StatusFactory factory = ServiceImpl.getInstance().getStatusFactory();
        LivelinessChangedStatus status =
            factory.createLivelinessChangedStatus();
        assert status != null;
        return status;
    }


    protected LivelinessChangedStatus(DataReader<?> source) {
        super(source);
    }



    // -----------------------------------------------------------------------
    // Methods
    // -----------------------------------------------------------------------

    /**
     * @return the aliveCount
     */
    public abstract int getAliveCount();

    /**
     * @return the notAliveCount
     */
    public abstract int getNotAliveCount();

    /**
     * @return the aliveCountChange
     */
    public abstract int getAliveCountChange();

    /**
     * @return the notAliveCountChange
     */
    public abstract int getNotAliveCountChange();

    public abstract void getLastPublicationHandle(InstanceHandle handle);

    @Override
    public abstract LivelinessChangedStatus clone();

} // class LivelinessChangedStatus
